/**
 * Draft mode's player pools: Premier League clubs by decade, 2010 to now. Each pool is a club's
 * notable players of that decade, with a position and an overall: close to his best FIFA rating
 * while at that club in that decade (recalled, and spot-checked against the rating databases;
 * treat it as a guide, not a record). A player appears in one pool only, so he can never meet
 * himself. Pools double as the league's other teams.
 */
import type { Archetype, Formation, Kit } from '../engine/index.ts'

export type Decade = '2010s' | '2020s'

export interface Pool {
  club: string
  shortName: string
  decade: Decade
  kit: Kit
  formation: Formation
  /**
   * Name, positions (his own first, then any secondary and tertiary: 'W/CM'), overall and, where
   * he isn't known by his surname, the name he's known by.
   */
  players: [name: string, positions: string, overall: number, knownAs?: string][]
}

const kit = (shirt: string, number: string, family: string): Kit => ({ shirt, number, family })
const RED = kit('#c8202f', '#ffffff', 'red')
const CLARET = kit('#7a1f2b', '#9fd3f0', 'red')
const ROYAL = kit('#1f3a8a', '#ffffff', 'blue')
const SKY = kit('#79b4e0', '#10263d', 'blue')
const WHITE = kit('#f2f2ee', '#1b2a4a', 'white')
const BLACK = kit('#232527', '#f2f2ee', 'black')

export const POOLS: Pool[] = [
  {
    club: 'Arsenal',
    shortName: 'ARS',
    decade: '2010s',
    kit: RED,
    formation: '4-3-3',
    players: [
      ['Wojciech Szczęsny', 'GK', 82],
      ['Bernd Leno', 'GK', 84],
      ['Laurent Koscielny', 'CB', 85],
      ['Per Mertesacker', 'CB', 83],
      ['Thomas Vermaelen', 'CB/FB', 82],
      ['Bacary Sagna', 'FB/CB', 82],
      ['Nacho Monreal', 'FB/CB', 80],
      ['Kieran Gibbs', 'FB/WM', 79],
      ['Héctor Bellerín', 'FB/WM', 83],
      ['Mikel Arteta', 'DM/CM', 82],
      ['Francis Coquelin', 'DM/CM', 80],
      ['Santi Cazorla', 'CM/W/DM', 86],
      ['Aaron Ramsey', 'CM/WM/W', 84],
      ['Jack Wilshere', 'CM', 82],
      ['Mesut Özil', 'CM/W', 89],
      ['Alexis Sánchez', 'W/ST', 88, 'Alexis'],
      ['Theo Walcott', 'W/ST', 82],
      ['Robin van Persie', 'ST', 88],
      ['Olivier Giroud', 'ST', 81],
      ['Pierre-Emerick Aubameyang', 'ST/W', 88],
    ],
  },
  {
    club: 'Arsenal',
    shortName: 'ARS',
    decade: '2020s',
    kit: RED,
    formation: '4-3-3',
    players: [
      ['David Raya', 'GK', 85],
      ['Aaron Ramsdale', 'GK', 82],
      ['William Saliba', 'CB', 87],
      ['Gabriel Magalhães', 'CB', 86, 'Gabriel'],
      ['Ben White', 'FB/CB', 84],
      ['Oleksandr Zinchenko', 'FB/CM', 81],
      ['Takehiro Tomiyasu', 'FB/CB', 80],
      ['Jurriën Timber', 'FB/CB', 81],
      ['Declan Rice', 'DM/CM', 87],
      ['Thomas Partey', 'DM/CM', 84],
      ['Martin Ødegaard', 'CM/W', 89],
      ['Granit Xhaka', 'CM/DM', 82],
      ['Mikel Merino', 'CM/DM/ST', 83],
      ['Bukayo Saka', 'W/WM', 88],
      ['Gabriel Martinelli', 'W/ST', 84],
      ['Leandro Trossard', 'W/ST/CM', 81],
      ['Kai Havertz', 'ST/CM', 83],
      ['Gabriel Jesus', 'ST/W', 82],
    ],
  },
  {
    club: 'Chelsea',
    shortName: 'CHE',
    decade: '2010s',
    kit: ROYAL,
    formation: '4-3-3',
    players: [
      ['Petr Čech', 'GK', 87],
      ['Thibaut Courtois', 'GK', 88],
      ['John Terry', 'CB', 86],
      ['Gary Cahill', 'CB', 83],
      ['David Luiz', 'CB/DM', 84],
      ['César Azpilicueta', 'FB/CB', 85],
      ['Branislav Ivanović', 'FB/CB', 84],
      ['Ashley Cole', 'FB', 85],
      ['Marcos Alonso', 'FB/WM', 82],
      ['N’Golo Kanté', 'DM/CM', 89],
      ['Nemanja Matić', 'DM/CM', 85],
      ['Frank Lampard', 'CM', 87],
      ['Cesc Fàbregas', 'CM/DM', 87],
      ['Ramires', 'CM/WM', 82],
      ['Eden Hazard', 'W/CM', 91],
      ['Willian', 'W/WM', 84],
      ['Juan Mata', 'CM/W', 86],
      ['Didier Drogba', 'ST', 86],
      ['Diego Costa', 'ST', 86, 'Diego Costa'],
    ],
  },
  {
    club: 'Chelsea',
    shortName: 'CHE',
    decade: '2020s',
    kit: ROYAL,
    formation: '4-3-3',
    players: [
      ['Édouard Mendy', 'GK', 83],
      ['Kepa Arrizabalaga', 'GK', 79, 'Kepa'],
      ['Thiago Silva', 'CB', 85, 'Thiago Silva'],
      ['Antonio Rüdiger', 'CB', 85],
      ['Levi Colwill', 'CB/FB', 80],
      ['Wesley Fofana', 'CB', 80],
      ['Reece James', 'FB/CB', 84],
      ['Ben Chilwell', 'FB/WM', 82],
      ['Marc Cucurella', 'FB/CB', 81],
      ['Moisés Caicedo', 'DM/CM/FB', 84],
      ['Jorginho', 'DM/CM', 86],
      ['Enzo Fernández', 'CM/DM', 84],
      ['Mateo Kovačić', 'CM/DM', 84],
      ['Mason Mount', 'CM/W', 83],
      ['Cole Palmer', 'W/CM', 87],
      ['Christian Pulisic', 'W/CM', 80],
      ['Noni Madueke', 'W', 77],
      ['Nicolas Jackson', 'ST/W', 78],
      ['Timo Werner', 'ST/W', 82],
    ],
  },
  {
    club: 'Liverpool',
    shortName: 'LIV',
    decade: '2010s',
    kit: RED,
    formation: '4-3-3',
    players: [
      ['Pepe Reina', 'GK', 85],
      ['Simon Mignolet', 'GK', 79],
      ['Jamie Carragher', 'CB/FB', 80],
      ['Martin Škrtel', 'CB', 81],
      ['Daniel Agger', 'CB', 82],
      ['Dejan Lovren', 'CB', 80],
      ['Glen Johnson', 'FB', 81],
      ['José Enrique', 'FB', 78],
      ['Alberto Moreno', 'FB', 76],
      ['Lucas Leiva', 'DM/CM', 80, 'Lucas'],
      ['Steven Gerrard', 'CM/DM', 88],
      ['Jordan Henderson', 'CM/DM', 84],
      ['James Milner', 'CM/FB/WM', 83],
      ['Emre Can', 'CM/DM', 81],
      ['Philippe Coutinho', 'W/CM', 87],
      ['Sadio Mané', 'W/ST', 90],
      ['Luis Suárez', 'ST/W', 88],
      ['Roberto Firmino', 'ST/CM', 87],
      ['Daniel Sturridge', 'ST/W', 83],
      ['Fernando Torres', 'ST', 88],
    ],
  },
  {
    club: 'Liverpool',
    shortName: 'LIV',
    decade: '2020s',
    kit: RED,
    formation: '4-3-3',
    players: [
      ['Alisson Becker', 'GK', 90, 'Alisson'],
      ['Caoimhín Kelleher', 'GK', 77],
      ['Virgil van Dijk', 'CB', 90],
      ['Ibrahima Konaté', 'CB', 84],
      ['Joël Matip', 'CB', 84],
      ['Joe Gomez', 'CB/FB', 80],
      ['Trent Alexander-Arnold', 'FB/CM', 87],
      ['Andrew Robertson', 'FB', 87],
      ['Fabinho', 'DM/CB', 87],
      ['Ryan Gravenberch', 'DM/CM', 83],
      ['Alexis Mac Allister', 'CM/DM', 85],
      ['Thiago Alcântara', 'CM/DM', 86, 'Thiago'],
      ['Dominik Szoboszlai', 'CM/W', 82],
      ['Mohamed Salah', 'W/ST', 90],
      ['Luis Díaz', 'W/ST', 84],
      ['Cody Gakpo', 'W/ST', 82],
      ['Diogo Jota', 'ST/W', 85],
      ['Darwin Núñez', 'ST/W', 80],
    ],
  },
  {
    club: 'Manchester City',
    shortName: 'MCI',
    decade: '2010s',
    kit: SKY,
    formation: '4-3-3',
    players: [
      ['Joe Hart', 'GK', 85],
      ['Claudio Bravo', 'GK', 84],
      ['Vincent Kompany', 'CB', 86],
      ['Aymeric Laporte', 'CB/FB', 87],
      ['Nicolás Otamendi', 'CB', 84],
      ['Joleon Lescott', 'CB', 80],
      ['Pablo Zabaleta', 'FB', 83],
      ['Aleksandar Kolarov', 'FB/CB', 81],
      ['Gaël Clichy', 'FB', 80],
      ['Fernandinho', 'DM/CB', 86],
      ['Yaya Touré', 'CM/DM', 87],
      ['David Silva', 'CM/W', 89],
      ['Kevin De Bruyne', 'CM/W', 91],
      ['Raheem Sterling', 'W/ST', 88],
      ['Leroy Sané', 'W', 86],
      ['Samir Nasri', 'W/CM', 83],
      ['Sergio Agüero', 'ST', 89],
      ['Carlos Tevez', 'ST/W', 85],
      ['Edin Džeko', 'ST', 83],
    ],
  },
  {
    club: 'Manchester City',
    shortName: 'MCI',
    decade: '2020s',
    kit: SKY,
    formation: '4-3-3',
    players: [
      ['Ederson', 'GK', 89],
      ['Stefan Ortega', 'GK', 80],
      ['Rúben Dias', 'CB', 88],
      ['John Stones', 'CB/DM', 85],
      ['Joško Gvardiol', 'CB/FB', 85],
      ['Manuel Akanji', 'CB/FB', 83],
      ['Nathan Aké', 'CB/FB', 82],
      ['Kyle Walker', 'FB/CB', 85],
      ['João Cancelo', 'FB/CM', 88],
      ['Rodri', 'DM/CB', 91],
      ['İlkay Gündoğan', 'CM/DM', 86],
      ['Bernardo Silva', 'CM/W', 88, 'Bernardo'],
      ['Phil Foden', 'W/CM', 88],
      ['Jack Grealish', 'W/CM', 84],
      ['Erling Haaland', 'ST', 91],
      ['Julián Álvarez', 'ST/W', 82],
    ],
  },
  {
    club: 'Manchester United',
    shortName: 'MUN',
    decade: '2010s',
    kit: RED,
    formation: '4-4-2',
    players: [
      ['David de Gea', 'GK', 91],
      ['Edwin van der Sar', 'GK', 86],
      ['Nemanja Vidić', 'CB', 87],
      ['Rio Ferdinand', 'CB', 85],
      ['Chris Smalling', 'CB', 81],
      ['Jonny Evans', 'CB', 79],
      ['Patrice Evra', 'FB', 84],
      ['Antonio Valencia', 'FB/WM', 83],
      ['Rafael', 'FB', 78],
      ['Michael Carrick', 'DM/CM/CB', 84],
      ['Paul Scholes', 'CM', 84],
      ['Paul Pogba', 'CM', 88],
      ['Ander Herrera', 'CM/DM', 82],
      ['Ryan Giggs', 'WM/CM', 82],
      ['Nani', 'WM/W', 84],
      ['Ashley Young', 'WM/FB/W', 81],
      ['Anthony Martial', 'W/ST', 82],
      ['Wayne Rooney', 'ST/CM', 88],
      ['Javier Hernández', 'ST', 81, 'Chicharito'],
      ['Zlatan Ibrahimović', 'ST', 90],
    ],
  },
  {
    club: 'Manchester United',
    shortName: 'MUN',
    decade: '2020s',
    kit: RED,
    formation: '4-3-3',
    players: [
      ['André Onana', 'GK', 83],
      ['Altay Bayındır', 'GK', 74],
      ['Raphaël Varane', 'CB', 86],
      ['Lisandro Martínez', 'CB/FB', 84],
      ['Harry Maguire', 'CB', 83],
      ['Victor Lindelöf', 'CB', 80],
      ['Luke Shaw', 'FB/CB', 84],
      ['Diogo Dalot', 'FB', 82],
      ['Aaron Wan-Bissaka', 'FB', 82],
      ['Casemiro', 'DM', 89],
      ['Scott McTominay', 'CM/DM', 80],
      ['Bruno Fernandes', 'CM/W', 88],
      ['Kobbie Mainoo', 'CM/DM', 78],
      ['Marcus Rashford', 'W/ST', 85],
      ['Jadon Sancho', 'W', 85],
      ['Alejandro Garnacho', 'W', 80],
      ['Amad Diallo', 'W', 80, 'Amad'],
      ['Cristiano Ronaldo', 'ST/W', 91],
      ['Edinson Cavani', 'ST', 85],
      ['Rasmus Højlund', 'ST', 78],
    ],
  },
  {
    club: 'Tottenham Hotspur',
    shortName: 'TOT',
    decade: '2010s',
    kit: WHITE,
    formation: '4-3-3',
    players: [
      ['Hugo Lloris', 'GK', 88],
      ['Brad Friedel', 'GK', 78],
      ['Jan Vertonghen', 'CB/FB', 86],
      ['Toby Alderweireld', 'CB', 87],
      ['Ledley King', 'CB', 80],
      ['Younès Kaboul', 'CB', 78],
      ['Danny Rose', 'FB/WM', 82],
      ['Ben Davies', 'FB/CB', 79],
      ['Benoît Assou-Ekotto', 'FB', 78],
      ['Serge Aurier', 'FB', 80],
      ['Scott Parker', 'DM/CM', 81],
      ['Eric Dier', 'DM/CB', 81],
      ['Mousa Dembélé', 'CM/DM', 84],
      ['Luka Modrić', 'CM', 85],
      ['Christian Eriksen', 'CM/W', 87],
      ['Dele Alli', 'CM/ST', 85],
      ['Rafael van der Vaart', 'CM/W', 84],
      ['Gareth Bale', 'W/WM/FB', 86],
      ['Aaron Lennon', 'W/WM', 79],
      ['Harry Kane', 'ST', 90],
      ['Emmanuel Adebayor', 'ST', 81],
    ],
  },
  {
    club: 'Tottenham Hotspur',
    shortName: 'TOT',
    decade: '2020s',
    kit: WHITE,
    formation: '4-3-3',
    players: [
      ['Guglielmo Vicario', 'GK', 83],
      ['Pierluigi Gollini', 'GK', 76],
      ['Cristian Romero', 'CB', 85],
      ['Micky van de Ven', 'CB/FB', 82],
      ['Radu Drăgușin', 'CB', 77],
      ['Pedro Porro', 'FB/WM', 82],
      ['Destiny Udogie', 'FB/WM', 80],
      ['Sergio Reguilón', 'FB', 79],
      ['Pierre-Emile Højbjerg', 'DM/CM', 82],
      ['Rodrigo Bentancur', 'DM/CM', 82],
      ['James Maddison', 'CM/W', 83],
      ['Pape Matar Sarr', 'CM', 79],
      ['Dejan Kulusevski', 'W/CM', 82],
      ['Son Heung-min', 'W/ST', 89, 'Son'],
      ['Brennan Johnson', 'W/ST', 79],
      ['Richarlison', 'ST/W', 82],
      ['Dominic Solanke', 'ST', 80],
    ],
  },
  {
    club: 'Everton',
    shortName: 'EVE',
    decade: '2010s',
    kit: ROYAL,
    formation: '4-3-3',
    players: [
      ['Tim Howard', 'GK', 81],
      ['Jordan Pickford', 'GK', 82],
      ['Phil Jagielka', 'CB', 81],
      ['Sylvain Distin', 'CB', 79],
      ['Michael Keane', 'CB', 80],
      ['Ashley Williams', 'CB', 78],
      ['Leighton Baines', 'FB/WM', 84],
      ['Séamus Coleman', 'FB', 81],
      ['Tony Hibbert', 'FB', 72],
      ['Idrissa Gueye', 'DM/CM', 82],
      ['Gareth Barry', 'DM/CM', 79],
      ['James McCarthy', 'CM/DM', 78],
      ['Marouane Fellaini', 'CM/ST/DM', 82],
      ['Ross Barkley', 'CM/W', 80],
      ['Gylfi Sigurðsson', 'CM/W', 82],
      ['Leon Osman', 'CM/WM', 77],
      ['Steven Pienaar', 'W/WM/CM', 80],
      ['Kevin Mirallas', 'W', 80],
      ['Romelu Lukaku', 'ST', 84],
      ['Tim Cahill', 'ST/CM', 79],
      ['Nikica Jelavić', 'ST', 77],
    ],
  },
  {
    club: 'Leicester City',
    shortName: 'LEI',
    decade: '2010s',
    kit: ROYAL,
    formation: '4-4-2',
    players: [
      ['Kasper Schmeichel', 'GK', 83],
      ['Ben Hamer', 'GK', 69],
      ['Wes Morgan', 'CB', 78],
      ['Robert Huth', 'CB', 79],
      ['Çağlar Söyüncü', 'CB', 79],
      ['Danny Simpson', 'FB', 76],
      ['Christian Fuchs', 'FB', 78],
      ['Ricardo Pereira', 'FB/WM', 82],
      ['Wilfred Ndidi', 'DM', 82],
      ['Danny Drinkwater', 'CM/DM', 80],
      ['Youri Tielemans', 'CM/DM', 82],
      ['Andy King', 'CM', 75],
      ['Riyad Mahrez', 'WM/W', 84],
      ['Marc Albrighton', 'WM/W/FB', 77],
      ['Demarai Gray', 'WM/W', 76],
      ['Harvey Barnes', 'W/WM', 79],
      ['Jamie Vardy', 'ST', 84],
      ['Shinji Okazaki', 'ST', 78],
      ['Kelechi Iheanacho', 'ST', 76],
      ['Leonardo Ulloa', 'ST', 74],
    ],
  },
  {
    club: 'Southampton',
    shortName: 'SOU',
    decade: '2010s',
    kit: RED,
    formation: '4-4-2',
    players: [
      ['Fraser Forster', 'GK', 80],
      ['Artur Boruc', 'GK', 75],
      ['José Fonte', 'CB', 80],
      ['Maya Yoshida', 'CB/FB', 76],
      ['Jan Bednarek', 'CB', 76],
      ['Nathaniel Clyne', 'FB', 80],
      ['Ryan Bertrand', 'FB', 81],
      ['Cédric Soares', 'FB', 78],
      ['Morgan Schneiderlin', 'DM/CM', 82],
      ['Victor Wanyama', 'DM/CM', 80],
      ['Oriol Romeu', 'DM/CB', 77],
      ['Adam Lallana', 'CM/W', 80],
      ['James Ward-Prowse', 'CM/DM', 80],
      ['Steven Davis', 'CM', 77],
      ['Dušan Tadić', 'WM/W/CM', 81],
      ['Nathan Redmond', 'WM/W', 77],
      ['Jay Rodriguez', 'ST/W', 78],
      ['Rickie Lambert', 'ST', 78],
      ['Graziano Pellè', 'ST', 80],
      ['Danny Ings', 'ST', 80],
      ['Shane Long', 'ST', 76],
    ],
  },
  {
    club: 'Newcastle United',
    shortName: 'NEW',
    decade: '2020s',
    kit: BLACK,
    formation: '4-3-3',
    players: [
      ['Nick Pope', 'GK', 83],
      ['Martin Dúbravka', 'GK', 77],
      ['Sven Botman', 'CB', 82],
      ['Fabian Schär', 'CB', 81],
      ['Dan Burn', 'CB/FB', 78],
      ['Jamaal Lascelles', 'CB', 76],
      ['Kieran Trippier', 'FB/WM', 84],
      ['Tino Livramento', 'FB', 78],
      ['Lewis Hall', 'FB/WM', 77],
      ['Bruno Guimarães', 'DM/CM', 85, 'Bruno Guimarães'],
      ['Sandro Tonali', 'CM/DM', 84],
      ['Joelinton', 'CM/ST/W', 81],
      ['Sean Longstaff', 'CM', 77],
      ['Anthony Gordon', 'W', 82],
      ['Allan Saint-Maximin', 'W', 80],
      ['Miguel Almirón', 'W/CM', 79],
      ['Jacob Murphy', 'W/WM', 77],
      ['Alexander Isak', 'ST', 86],
      ['Callum Wilson', 'ST', 80],
    ],
  },
  {
    club: 'Aston Villa',
    shortName: 'AVL',
    decade: '2020s',
    kit: CLARET,
    formation: '4-3-3',
    players: [
      ['Emiliano Martínez', 'GK', 86],
      ['Robin Olsen', 'GK', 74],
      ['Ezri Konsa', 'CB/FB', 81],
      ['Pau Torres', 'CB', 82],
      ['Tyrone Mings', 'CB', 79],
      ['Diego Carlos', 'CB', 78, 'Diego Carlos'],
      ['Matty Cash', 'FB/WM', 79],
      ['Lucas Digne', 'FB', 79],
      ['Boubacar Kamara', 'DM/CB', 81],
      ['Amadou Onana', 'DM/CM', 80],
      ['Douglas Luiz', 'CM/DM', 82, 'Douglas Luiz'],
      ['John McGinn', 'CM/W', 80],
      ['Jacob Ramsey', 'CM/W', 77],
      ['Morgan Rogers', 'W/CM', 80],
      ['Leon Bailey', 'W', 80],
      ['Moussa Diaby', 'W', 81],
      ['Emiliano Buendía', 'W/CM', 79],
      ['Ollie Watkins', 'ST/W', 84],
      ['Jhon Durán', 'ST', 76],
    ],
  },
  {
    club: 'West Ham United',
    shortName: 'WHU',
    decade: '2020s',
    kit: CLARET,
    formation: '4-3-3',
    players: [
      ['Łukasz Fabiański', 'GK', 79],
      ['Alphonse Areola', 'GK', 79],
      ['Kurt Zouma', 'CB', 80],
      ['Angelo Ogbonna', 'CB', 79],
      ['Nayef Aguerd', 'CB', 79],
      ['Craig Dawson', 'CB', 77],
      ['Vladimír Coufal', 'FB', 78],
      ['Aaron Cresswell', 'FB/CB', 78],
      ['Emerson Palmieri', 'FB', 78, 'Emerson'],
      ['Tomáš Souček', 'DM/CM', 80],
      ['Edson Álvarez', 'DM/CB', 80],
      ['Lucas Paquetá', 'CM/W', 83],
      ['Pablo Fornals', 'CM/W', 78],
      ['Jarrod Bowen', 'W/ST', 83],
      ['Mohammed Kudus', 'W/CM', 81],
      ['Saïd Benrahma', 'W', 78],
      ['Michail Antonio', 'ST/W', 79],
      ['Niclas Füllkrug', 'ST', 79],
    ],
  },
  {
    club: 'Brighton & Hove Albion',
    shortName: 'BHA',
    decade: '2020s',
    kit: kit('#2a5fb0', '#ffffff', 'blue'),
    formation: '4-3-3',
    players: [
      ['Bart Verbruggen', 'GK', 78],
      ['Robert Sánchez', 'GK', 79],
      ['Lewis Dunk', 'CB', 81],
      ['Jan Paul van Hecke', 'CB', 79],
      ['Adam Webster', 'CB', 78],
      ['Pervis Estupiñán', 'FB', 80],
      ['Joël Veltman', 'FB/CB', 77],
      ['Tariq Lamptey', 'FB/WM', 76],
      ['Yves Bissouma', 'DM/CM', 80],
      ['Carlos Baleba', 'DM/CM', 79],
      ['Pascal Groß', 'CM/FB/W', 82],
      ['Billy Gilmour', 'CM/DM', 77],
      ['Kaoru Mitoma', 'W', 81],
      ['Solly March', 'W/FB', 79],
      ['Simon Adingra', 'W', 77],
      ['João Pedro', 'ST/CM', 80, 'João Pedro'],
      ['Danny Welbeck', 'ST', 77],
      ['Evan Ferguson', 'ST', 77],
    ],
  },
  {
    club: 'Crystal Palace',
    shortName: 'CRY',
    decade: '2020s',
    kit: kit('#1b458f', '#f0c330', 'blue'),
    formation: '4-3-3',
    players: [
      ['Dean Henderson', 'GK', 80],
      ['Vicente Guaita', 'GK', 77],
      ['Marc Guéhi', 'CB', 82],
      ['Joachim Andersen', 'CB', 81],
      ['Maxence Lacroix', 'CB', 80],
      ['Chris Richards', 'CB/FB', 76],
      ['Daniel Muñoz', 'FB/WM', 81],
      ['Tyrick Mitchell', 'FB', 78],
      ['Joel Ward', 'FB', 75],
      ['Adam Wharton', 'DM/CM', 79],
      ['Cheick Doucouré', 'DM', 79],
      ['Jefferson Lerma', 'DM/CM', 79],
      ['Eberechi Eze', 'CM/W', 83],
      ['Luka Milivojević', 'DM/CM', 79],
      ['Michael Olise', 'W/CM', 82],
      ['Wilfried Zaha', 'W/ST', 83],
      ['Ismaïla Sarr', 'W', 78],
      ['Jean-Philippe Mateta', 'ST', 80],
      ['Odsonne Édouard', 'ST', 76],
    ],
  },
]

/** Left-footed players (everyone else in the pools is right-footed). */
export const LEFT_FOOTED = new Set([
  'Mesut Özil', 'Kieran Gibbs', 'Nacho Monreal', 'Olivier Giroud', 'Robin van Persie',
  'Bukayo Saka', 'Martin Ødegaard', 'Oleksandr Zinchenko', 'Gabriel Magalhães',
  'Kai Havertz', 'Ashley Cole', 'Marcos Alonso', 'Juan Mata', 'Marc Cucurella',
  'Ben Chilwell', 'Cole Palmer', 'Levi Colwill', 'Noni Madueke', 'Daniel Sturridge',
  'Alberto Moreno', 'Daniel Agger', 'José Enrique', 'Mohamed Salah', 'Andrew Robertson',
  'David Silva', 'Aleksandar Kolarov', 'Gaël Clichy', 'Aymeric Laporte', 'Leroy Sané',
  'Phil Foden', 'Joško Gvardiol', 'Nathan Aké', 'Bernardo Silva', 'Erling Haaland',
  'Ederson', 'Patrice Evra', 'Ryan Giggs', 'Luke Shaw', 'Lisandro Martínez', 'Amad Diallo',
  'Rasmus Højlund', 'Gareth Bale', 'Danny Rose', 'Ben Davies', 'Benoît Assou-Ekotto',
  'Jan Vertonghen', 'Rafael van der Vaart', 'Destiny Udogie', 'Sergio Reguilón',
  'Micky van de Ven', 'Dejan Kulusevski', 'Leighton Baines', 'Sylvain Distin',
  'Romelu Lukaku', 'Gareth Barry', 'Riyad Mahrez', 'Christian Fuchs', 'Dušan Tadić',
  'Ryan Bertrand', 'Sven Botman', 'Dan Burn', 'Lewis Hall', 'Miguel Almirón', 'Lucas Digne',
  'Pau Torres', 'Tyrone Mings', 'Leon Bailey', 'Moussa Diaby', 'John McGinn',
  'Aaron Cresswell', 'Emerson Palmieri', 'Angelo Ogbonna', 'Nayef Aguerd', 'Jarrod Bowen',
  'Mohammed Kudus', 'Lucas Paquetá', 'Pervis Estupiñán', 'Solly March', 'Tyrick Mitchell',
  'Michael Olise', 'Odsonne Édouard', 'Adam Wharton',
])

/**
 * Weak foot, in the familiar 1-5 stars, where it isn't the usual 3: the two-footed (5) and nearly
 * so (4), and the famously one-footed (2).
 */
export const WEAK_FOOT: Record<string, number> = {
  'Santi Cazorla': 5, 'Son Heung-min': 5, 'Nani': 5, 'Kevin De Bruyne': 5, 'Ashley Young': 5,
  'Leandro Trossard': 5, 'Mousa Dembélé': 5, 'Harry Kane': 5, 'Sadio Mané': 4,
  'Eden Hazard': 4, 'Luka Modrić': 4, 'Diogo Jota': 4, 'Paul Pogba': 4,
  'Cristiano Ronaldo': 4, 'Zlatan Ibrahimović': 4, 'Sergio Agüero': 4, 'Wayne Rooney': 4,
  'Christian Eriksen': 4, 'Julián Álvarez': 4, 'Kaoru Mitoma': 4, 'Eberechi Eze': 4,
  'João Cancelo': 4, 'Marcus Rashford': 4, 'Steven Gerrard': 4, 'Frank Lampard': 4,
  'Edinson Cavani': 4, 'Bruno Fernandes': 4, 'Dele Alli': 4, 'Martin Ødegaard': 4,
  'Rodri': 4, 'Thiago Alcântara': 4, 'Mesut Özil': 2, 'Riyad Mahrez': 2, 'Leroy Sané': 2,
  'Gareth Bale': 2, 'Andrew Robertson': 2,
}

/**
 * How the best-known players play their position (see engine/archetypes.ts). Anyone not listed
 * gets one read off his attributes.
 */
export const ARCHETYPE: Record<string, Archetype> = {
  'Erling Haaland': 'poacher', 'Sergio Agüero': 'poacher', 'Robin van Persie': 'poacher',
  'Jamie Vardy': 'poacher', 'Fernando Torres': 'poacher', 'Daniel Sturridge': 'poacher',
  'Alexander Isak': 'poacher', 'Ollie Watkins': 'poacher', 'Edinson Cavani': 'poacher',
  'Cristiano Ronaldo': 'poacher', 'Rasmus Højlund': 'poacher', 'Darwin Núñez': 'poacher',
  'Diogo Jota': 'poacher', 'Nicolas Jackson': 'poacher', 'Timo Werner': 'poacher',
  'Richarlison': 'poacher', 'Callum Wilson': 'poacher', 'Danny Ings': 'poacher',
  'Shane Long': 'poacher', 'Javier Hernández': 'poacher', 'Nikica Jelavić': 'poacher',
  'Kelechi Iheanacho': 'poacher', 'Julián Álvarez': 'poacher', 'Jhon Durán': 'poacher',
  'Odsonne Édouard': 'poacher', 'Jay Rodriguez': 'poacher',
  'Pierre-Emerick Aubameyang': 'poacher', 'Luis Suárez': 'poacher', 'Gabriel Jesus': 'poacher',
  'Jean-Philippe Mateta': 'poacher', 'Olivier Giroud': 'targetMan', 'Didier Drogba': 'targetMan',
  'Diego Costa': 'targetMan', 'Zlatan Ibrahimović': 'targetMan', 'Romelu Lukaku': 'targetMan',
  'Edin Džeko': 'targetMan', 'Graziano Pellè': 'targetMan', 'Rickie Lambert': 'targetMan',
  'Michail Antonio': 'targetMan', 'Niclas Füllkrug': 'targetMan',
  'Emmanuel Adebayor': 'targetMan', 'Tim Cahill': 'targetMan', 'Leonardo Ulloa': 'targetMan',
  'Evan Ferguson': 'targetMan', 'Danny Welbeck': 'targetMan', 'Harry Kane': 'falseNine',
  'Roberto Firmino': 'falseNine', 'Wayne Rooney': 'falseNine', 'Kai Havertz': 'falseNine',
  'Carlos Tevez': 'falseNine', 'Dominic Solanke': 'falseNine', 'Shinji Okazaki': 'falseNine',
  'João Pedro': 'falseNine', 'Mohamed Salah': 'insideForward', 'Eden Hazard': 'insideForward',
  'Raheem Sterling': 'insideForward', 'Sadio Mané': 'insideForward',
  'Son Heung-min': 'insideForward', 'Bukayo Saka': 'insideForward',
  'Gabriel Martinelli': 'insideForward', 'Phil Foden': 'insideForward',
  'Riyad Mahrez': 'insideForward', 'Gareth Bale': 'insideForward',
  'Philippe Coutinho': 'insideForward', 'Alexis Sánchez': 'insideForward',
  'Marcus Rashford': 'insideForward', 'Cole Palmer': 'insideForward',
  'Noni Madueke': 'insideForward', 'Christian Pulisic': 'insideForward',
  'Luis Díaz': 'insideForward', 'Cody Gakpo': 'insideForward', 'Jarrod Bowen': 'insideForward',
  'Mohammed Kudus': 'insideForward', 'Michael Olise': 'insideForward',
  'Dejan Kulusevski': 'insideForward', 'Leandro Trossard': 'insideForward',
  'Anthony Martial': 'insideForward', 'Harvey Barnes': 'insideForward',
  'Kevin Mirallas': 'insideForward', 'Saïd Benrahma': 'insideForward',
  'Morgan Rogers': 'insideForward', 'Emiliano Buendía': 'insideForward',
  'Juan Mata': 'playmaker', 'Samir Nasri': 'insideForward', 'Leroy Sané': 'winger',
  'Theo Walcott': 'winger', 'Aaron Lennon': 'winger', 'Jadon Sancho': 'winger',
  'Alejandro Garnacho': 'winger', 'Amad Diallo': 'winger', 'Anthony Gordon': 'winger',
  'Allan Saint-Maximin': 'winger', 'Miguel Almirón': 'winger', 'Wilfried Zaha': 'winger',
  'Kaoru Mitoma': 'winger', 'Solly March': 'winger', 'Leon Bailey': 'winger',
  'Moussa Diaby': 'winger', 'Brennan Johnson': 'winger', 'Willian': 'winger', 'Nani': 'winger',
  'Ryan Giggs': 'winger', 'Ashley Young': 'winger', 'Marc Albrighton': 'winger',
  'Steven Pienaar': 'winger', 'Demarai Gray': 'winger', 'Nathan Redmond': 'winger',
  'Simon Adingra': 'winger', 'Jacob Murphy': 'winger', 'Ismaïla Sarr': 'winger',
  'Jack Grealish': 'winger', 'Dušan Tadić': 'winger', 'Andrew Robertson': 'overlapping',
  'Luke Shaw': 'overlapping', 'Leighton Baines': 'overlapping', 'Ashley Cole': 'overlapping',
  'Marcos Alonso': 'overlapping', 'Ben Chilwell': 'overlapping', 'Reece James': 'overlapping',
  'Danny Rose': 'overlapping', 'Kieran Trippier': 'overlapping',
  'Pervis Estupiñán': 'overlapping', 'Destiny Udogie': 'overlapping',
  'Pedro Porro': 'overlapping', 'Pablo Zabaleta': 'overlapping', 'Patrice Evra': 'overlapping',
  'Antonio Valencia': 'overlapping', 'Rafael': 'overlapping', 'Diogo Dalot': 'overlapping',
  'Séamus Coleman': 'overlapping', 'Nathaniel Clyne': 'overlapping',
  'Ryan Bertrand': 'overlapping', 'Ricardo Pereira': 'overlapping', 'Matty Cash': 'overlapping',
  'Lucas Digne': 'overlapping', 'Aaron Cresswell': 'overlapping',
  'Vladimír Coufal': 'overlapping', 'Daniel Muñoz': 'overlapping',
  'Tyrick Mitchell': 'overlapping', 'Tino Livramento': 'overlapping',
  'Tariq Lamptey': 'overlapping', 'Benoît Assou-Ekotto': 'overlapping',
  'Serge Aurier': 'overlapping', 'Sergio Reguilón': 'overlapping', 'Glen Johnson': 'overlapping',
  'Alberto Moreno': 'overlapping', 'José Enrique': 'overlapping',
  'Aleksandar Kolarov': 'overlapping', 'Gaël Clichy': 'overlapping',
  'Bacary Sagna': 'overlapping', 'Kieran Gibbs': 'overlapping', 'Héctor Bellerín': 'overlapping',
  'Kyle Walker': 'overlapping', 'Trent Alexander-Arnold': 'inverted', 'João Cancelo': 'inverted',
  'Oleksandr Zinchenko': 'inverted', 'Ben White': 'inverted', 'Jurriën Timber': 'inverted',
  'Marc Cucurella': 'inverted', 'Lewis Hall': 'inverted',
  'César Azpilicueta': 'defensiveFullBack', 'Branislav Ivanović': 'defensiveFullBack',
  'Takehiro Tomiyasu': 'defensiveFullBack', 'Aaron Wan-Bissaka': 'defensiveFullBack',
  'Nacho Monreal': 'defensiveFullBack', 'Christian Fuchs': 'defensiveFullBack',
  'Danny Simpson': 'defensiveFullBack', 'Joël Veltman': 'defensiveFullBack',
  'Ben Davies': 'defensiveFullBack', 'Tony Hibbert': 'defensiveFullBack',
  'Joel Ward': 'defensiveFullBack', 'Cédric Soares': 'defensiveFullBack',
  'Emerson Palmieri': 'defensiveFullBack', 'Virgil van Dijk': 'ballPlayer',
  'John Stones': 'ballPlayer', 'Aymeric Laporte': 'ballPlayer', 'David Luiz': 'ballPlayer',
  'Jan Vertonghen': 'ballPlayer', 'Toby Alderweireld': 'ballPlayer',
  'William Saliba': 'ballPlayer', 'Rio Ferdinand': 'ballPlayer', 'Thiago Silva': 'ballPlayer',
  'Lisandro Martínez': 'ballPlayer', 'Harry Maguire': 'ballPlayer', 'Lewis Dunk': 'ballPlayer',
  'Marc Guéhi': 'ballPlayer', 'Sven Botman': 'ballPlayer', 'Daniel Agger': 'ballPlayer',
  'Per Mertesacker': 'ballPlayer', 'Pau Torres': 'ballPlayer', 'Nathan Aké': 'ballPlayer',
  'Joško Gvardiol': 'ballPlayer', 'Rúben Dias': 'ballPlayer', 'Joël Matip': 'ballPlayer',
  'Micky van de Ven': 'ballPlayer', 'Levi Colwill': 'ballPlayer',
  'Jan Paul van Hecke': 'ballPlayer', 'Fabian Schär': 'ballPlayer',
  'Joachim Andersen': 'ballPlayer', 'Manuel Akanji': 'ballPlayer',
  'Vincent Kompany': 'ballPlayer', 'John Terry': 'stopper', 'Nemanja Vidić': 'stopper',
  'Gabriel Magalhães': 'stopper', 'Antonio Rüdiger': 'stopper', 'Cristian Romero': 'stopper',
  'Raphaël Varane': 'stopper', 'Ibrahima Konaté': 'stopper', 'Martin Škrtel': 'stopper',
  'Robert Huth': 'stopper', 'Wes Morgan': 'stopper', 'Jamie Carragher': 'stopper',
  'Laurent Koscielny': 'stopper', 'Gary Cahill': 'stopper', 'Phil Jagielka': 'stopper',
  'Tyrone Mings': 'stopper', 'Kurt Zouma': 'stopper', 'Nicolás Otamendi': 'stopper',
  'Chris Smalling': 'stopper', 'Younès Kaboul': 'stopper', 'Ledley King': 'stopper',
  'Dan Burn': 'stopper', 'Craig Dawson': 'stopper', 'Çağlar Söyüncü': 'stopper',
  'José Fonte': 'stopper', 'Ezri Konsa': 'stopper', 'Diego Carlos': 'stopper',
  'Wesley Fofana': 'stopper', 'Thomas Vermaelen': 'stopper', 'Jorginho': 'deepPlaymaker',
  'Michael Carrick': 'deepPlaymaker', 'Mikel Arteta': 'deepPlaymaker', 'Rodri': 'deepPlaymaker',
  'Adam Wharton': 'deepPlaymaker', 'Bruno Guimarães': 'deepPlaymaker',
  'Luka Milivojević': 'deepPlaymaker', 'Fabinho': 'deepPlaymaker',
  'Declan Rice': 'deepPlaymaker', 'Thomas Partey': 'deepPlaymaker',
  'Yves Bissouma': 'deepPlaymaker', 'Boubacar Kamara': 'deepPlaymaker', 'Fernandinho': 'anchor',
  'Nemanja Matić': 'anchor', 'Casemiro': 'anchor', 'Lucas Leiva': 'anchor',
  'Scott Parker': 'anchor', 'Eric Dier': 'anchor', 'Morgan Schneiderlin': 'anchor',
  'Victor Wanyama': 'anchor', 'Wilfred Ndidi': 'anchor', 'Tomáš Souček': 'anchor',
  'Edson Álvarez': 'anchor', 'Cheick Doucouré': 'anchor', 'Carlos Baleba': 'anchor',
  'Rodrigo Bentancur': 'anchor', 'Pierre-Emile Højbjerg': 'anchor', 'Amadou Onana': 'anchor',
  'Ryan Gravenberch': 'anchor', 'Oriol Romeu': 'anchor', 'Gareth Barry': 'anchor',
  'Francis Coquelin': 'anchor', 'N’Golo Kanté': 'ballWinner', 'Idrissa Gueye': 'ballWinner',
  'Moisés Caicedo': 'ballWinner', 'Jefferson Lerma': 'ballWinner', 'Ander Herrera': 'ballWinner',
  'Emre Can': 'ballWinner', 'Kevin De Bruyne': 'playmaker', 'David Silva': 'playmaker',
  'Mesut Özil': 'playmaker', 'Santi Cazorla': 'playmaker', 'Martin Ødegaard': 'playmaker',
  'Bruno Fernandes': 'playmaker', 'Christian Eriksen': 'playmaker', 'Cesc Fàbregas': 'playmaker',
  'Luka Modrić': 'playmaker', 'James Maddison': 'playmaker', 'Lucas Paquetá': 'playmaker',
  'Thiago Alcântara': 'playmaker', 'Mateo Kovačić': 'playmaker', 'Bernardo Silva': 'playmaker',
  'Enzo Fernández': 'playmaker', 'Youri Tielemans': 'playmaker', 'Pascal Groß': 'playmaker',
  'Eberechi Eze': 'playmaker', 'James Ward-Prowse': 'playmaker', 'Adam Lallana': 'playmaker',
  'Paul Scholes': 'playmaker', 'Rafael van der Vaart': 'playmaker', 'Mousa Dembélé': 'playmaker',
  'Danny Drinkwater': 'playmaker', 'Alexis Mac Allister': 'playmaker',
  'Mason Mount': 'playmaker', 'Gylfi Sigurðsson': 'playmaker', 'İlkay Gündoğan': 'playmaker',
  'Mikel Merino': 'playmaker', 'Granit Xhaka': 'playmaker', 'Frank Lampard': 'boxToBox',
  'Steven Gerrard': 'boxToBox', 'Jordan Henderson': 'boxToBox', 'Aaron Ramsey': 'boxToBox',
  'Yaya Touré': 'boxToBox', 'Paul Pogba': 'boxToBox', 'Dele Alli': 'boxToBox',
  'Ross Barkley': 'boxToBox', 'Marouane Fellaini': 'boxToBox', 'Scott McTominay': 'boxToBox',
  'John McGinn': 'boxToBox', 'Joelinton': 'boxToBox', 'Dominik Szoboszlai': 'boxToBox',
  'James Milner': 'boxToBox', 'Ramires': 'boxToBox', 'Jack Wilshere': 'boxToBox',
  'Sandro Tonali': 'boxToBox', 'Douglas Luiz': 'boxToBox', 'Jacob Ramsey': 'boxToBox',
  'Kobbie Mainoo': 'boxToBox', 'Pape Matar Sarr': 'boxToBox', 'Leon Osman': 'boxToBox',
  'James McCarthy': 'boxToBox', 'Sean Longstaff': 'boxToBox', 'Billy Gilmour': 'boxToBox',
  'Pablo Fornals': 'boxToBox', 'Andy King': 'boxToBox', 'Steven Davis': 'boxToBox',
  'Alisson Becker': 'sweeperKeeper', 'Ederson': 'sweeperKeeper', 'Hugo Lloris': 'sweeperKeeper',
  'David Raya': 'sweeperKeeper', 'Bart Verbruggen': 'sweeperKeeper',
  'Robert Sánchez': 'sweeperKeeper', 'Guglielmo Vicario': 'sweeperKeeper',
  'André Onana': 'sweeperKeeper', 'Stefan Ortega': 'sweeperKeeper',
  'Bernd Leno': 'sweeperKeeper', 'Claudio Bravo': 'sweeperKeeper',
  'Aaron Ramsdale': 'sweeperKeeper', 'Jordan Pickford': 'sweeperKeeper',
}
