/**
 * Draft mode's player pools: Premier League clubs by decade, 2010 to now. Each pool is a club's
 * notable players of that decade, with a position and an overall (our own rough estimate, 60–95,
 * of the player at his best there). A player appears in one pool only, so he can never meet
 * himself. Pools double as the league's other teams.
 */
import type { Formation, Kit, Role } from '../engine/index.ts'

export type Decade = '2010s' | '2020s'

export interface Pool {
  club: string
  shortName: string
  decade: Decade
  kit: Kit
  formation: Formation
  players: [name: string, role: Role, overall: number][]
}

const kit = (shirt: string, number: string, family: string): Kit => ({ shirt, number, family })
const RED = kit('#c8202f', '#ffffff', 'red')
const CLARET = kit('#7a1f2b', '#9fd3f0', 'red')
const ROYAL = kit('#1f3a8a', '#ffffff', 'blue')
const SKY = kit('#79b4e0', '#10263d', 'blue')
const WHITE = kit('#f2f2ee', '#1b2a4a', 'white')
const BLACK = kit('#232527', '#f2f2ee', 'black')

export const POOLS: Pool[] = [
  {
    club: 'Arsenal',
    shortName: 'ARS',
    decade: '2010s',
    kit: RED,
    formation: '4-3-3',
    players: [
      ['Wojciech Szczęsny', 'GK', 80],
      ['Bernd Leno', 'GK', 79],
      ['Laurent Koscielny', 'CB', 84],
      ['Per Mertesacker', 'CB', 81],
      ['Thomas Vermaelen', 'CB', 80],
      ['Bacary Sagna', 'FB', 81],
      ['Nacho Monreal', 'FB', 79],
      ['Kieran Gibbs', 'FB', 77],
      ['Héctor Bellerín', 'FB', 80],
      ['Mikel Arteta', 'DM', 81],
      ['Francis Coquelin', 'DM', 76],
      ['Santi Cazorla', 'CM', 86],
      ['Aaron Ramsey', 'CM', 83],
      ['Jack Wilshere', 'CM', 81],
      ['Mesut Özil', 'CM', 87],
      ['Alexis Sánchez', 'W', 88],
      ['Theo Walcott', 'W', 80],
      ['Robin van Persie', 'ST', 89],
      ['Olivier Giroud', 'ST', 81],
      ['Pierre-Emerick Aubameyang', 'ST', 86],
    ],
  },
  {
    club: 'Arsenal',
    shortName: 'ARS',
    decade: '2020s',
    kit: RED,
    formation: '4-3-3',
    players: [
      ['David Raya', 'GK', 84],
      ['Aaron Ramsdale', 'GK', 80],
      ['William Saliba', 'CB', 87],
      ['Gabriel Magalhães', 'CB', 86],
      ['Ben White', 'FB', 83],
      ['Oleksandr Zinchenko', 'FB', 80],
      ['Takehiro Tomiyasu', 'FB', 79],
      ['Jurriën Timber', 'FB', 80],
      ['Declan Rice', 'DM', 88],
      ['Thomas Partey', 'DM', 83],
      ['Martin Ødegaard', 'CM', 89],
      ['Granit Xhaka', 'CM', 82],
      ['Mikel Merino', 'CM', 82],
      ['Bukayo Saka', 'W', 89],
      ['Gabriel Martinelli', 'W', 84],
      ['Leandro Trossard', 'W', 81],
      ['Kai Havertz', 'ST', 83],
      ['Gabriel Jesus', 'ST', 81],
    ],
  },
  {
    club: 'Chelsea',
    shortName: 'CHE',
    decade: '2010s',
    kit: ROYAL,
    formation: '4-3-3',
    players: [
      ['Petr Čech', 'GK', 88],
      ['Thibaut Courtois', 'GK', 86],
      ['John Terry', 'CB', 87],
      ['Gary Cahill', 'CB', 82],
      ['David Luiz', 'CB', 83],
      ['César Azpilicueta', 'FB', 84],
      ['Branislav Ivanović', 'FB', 83],
      ['Ashley Cole', 'FB', 85],
      ['Marcos Alonso', 'FB', 79],
      ['N’Golo Kanté', 'DM', 89],
      ['Nemanja Matić', 'DM', 84],
      ['Frank Lampard', 'CM', 86],
      ['Cesc Fàbregas', 'CM', 86],
      ['Ramires', 'CM', 80],
      ['Eden Hazard', 'W', 91],
      ['Willian', 'W', 82],
      ['Juan Mata', 'W', 84],
      ['Didier Drogba', 'ST', 86],
      ['Diego Costa', 'ST', 86],
    ],
  },
  {
    club: 'Chelsea',
    shortName: 'CHE',
    decade: '2020s',
    kit: ROYAL,
    formation: '4-3-3',
    players: [
      ['Édouard Mendy', 'GK', 82],
      ['Kepa Arrizabalaga', 'GK', 78],
      ['Thiago Silva', 'CB', 86],
      ['Antonio Rüdiger', 'CB', 85],
      ['Levi Colwill', 'CB', 80],
      ['Wesley Fofana', 'CB', 79],
      ['Reece James', 'FB', 85],
      ['Ben Chilwell', 'FB', 82],
      ['Marc Cucurella', 'FB', 80],
      ['Moisés Caicedo', 'DM', 85],
      ['Jorginho', 'DM', 83],
      ['Enzo Fernández', 'CM', 84],
      ['Mateo Kovačić', 'CM', 83],
      ['Mason Mount', 'CM', 83],
      ['Cole Palmer', 'W', 88],
      ['Christian Pulisic', 'W', 80],
      ['Noni Madueke', 'W', 78],
      ['Nicolas Jackson', 'ST', 78],
      ['Timo Werner', 'ST', 78],
    ],
  },
  {
    club: 'Liverpool',
    shortName: 'LIV',
    decade: '2010s',
    kit: RED,
    formation: '4-3-3',
    players: [
      ['Pepe Reina', 'GK', 83],
      ['Simon Mignolet', 'GK', 77],
      ['Jamie Carragher', 'CB', 80],
      ['Martin Škrtel', 'CB', 80],
      ['Daniel Agger', 'CB', 81],
      ['Dejan Lovren', 'CB', 78],
      ['Glen Johnson', 'FB', 80],
      ['José Enrique', 'FB', 76],
      ['Alberto Moreno', 'FB', 75],
      ['Lucas Leiva', 'DM', 78],
      ['Steven Gerrard', 'CM', 87],
      ['Jordan Henderson', 'CM', 83],
      ['James Milner', 'CM', 82],
      ['Emre Can', 'CM', 78],
      ['Philippe Coutinho', 'W', 86],
      ['Sadio Mané', 'W', 88],
      ['Luis Suárez', 'ST', 91],
      ['Roberto Firmino', 'ST', 85],
      ['Daniel Sturridge', 'ST', 83],
      ['Fernando Torres', 'ST', 84],
    ],
  },
  {
    club: 'Liverpool',
    shortName: 'LIV',
    decade: '2020s',
    kit: RED,
    formation: '4-3-3',
    players: [
      ['Alisson Becker', 'GK', 90],
      ['Caoimhín Kelleher', 'GK', 77],
      ['Virgil van Dijk', 'CB', 90],
      ['Ibrahima Konaté', 'CB', 84],
      ['Joël Matip', 'CB', 82],
      ['Joe Gomez', 'CB', 79],
      ['Trent Alexander-Arnold', 'FB', 87],
      ['Andrew Robertson', 'FB', 86],
      ['Fabinho', 'DM', 85],
      ['Ryan Gravenberch', 'DM', 83],
      ['Alexis Mac Allister', 'CM', 85],
      ['Thiago Alcântara', 'CM', 85],
      ['Dominik Szoboszlai', 'CM', 82],
      ['Mohamed Salah', 'W', 91],
      ['Luis Díaz', 'W', 84],
      ['Cody Gakpo', 'W', 82],
      ['Diogo Jota', 'ST', 84],
      ['Darwin Núñez', 'ST', 79],
    ],
  },
  {
    club: 'Manchester City',
    shortName: 'MCI',
    decade: '2010s',
    kit: SKY,
    formation: '4-3-3',
    players: [
      ['Joe Hart', 'GK', 84],
      ['Claudio Bravo', 'GK', 76],
      ['Vincent Kompany', 'CB', 87],
      ['Aymeric Laporte', 'CB', 85],
      ['Nicolás Otamendi', 'CB', 81],
      ['Joleon Lescott', 'CB', 79],
      ['Pablo Zabaleta', 'FB', 83],
      ['Aleksandar Kolarov', 'FB', 80],
      ['Gaël Clichy', 'FB', 79],
      ['Fernandinho', 'DM', 86],
      ['Yaya Touré', 'CM', 89],
      ['David Silva', 'CM', 90],
      ['Kevin De Bruyne', 'CM', 91],
      ['Raheem Sterling', 'W', 86],
      ['Leroy Sané', 'W', 84],
      ['Samir Nasri', 'W', 82],
      ['Sergio Agüero', 'ST', 91],
      ['Carlos Tevez', 'ST', 85],
      ['Edin Džeko', 'ST', 81],
    ],
  },
  {
    club: 'Manchester City',
    shortName: 'MCI',
    decade: '2020s',
    kit: SKY,
    formation: '4-3-3',
    players: [
      ['Ederson', 'GK', 88],
      ['Stefan Ortega', 'GK', 78],
      ['Rúben Dias', 'CB', 88],
      ['John Stones', 'CB', 85],
      ['Joško Gvardiol', 'CB', 84],
      ['Manuel Akanji', 'CB', 82],
      ['Nathan Aké', 'CB', 81],
      ['Kyle Walker', 'FB', 85],
      ['João Cancelo', 'FB', 86],
      ['Rodri', 'DM', 91],
      ['İlkay Gündoğan', 'CM', 86],
      ['Bernardo Silva', 'CM', 87],
      ['Phil Foden', 'W', 88],
      ['Jack Grealish', 'W', 82],
      ['Erling Haaland', 'ST', 91],
      ['Julián Álvarez', 'ST', 83],
    ],
  },
  {
    club: 'Manchester United',
    shortName: 'MUN',
    decade: '2010s',
    kit: RED,
    formation: '4-4-2',
    players: [
      ['David de Gea', 'GK', 87],
      ['Edwin van der Sar', 'GK', 84],
      ['Nemanja Vidić', 'CB', 86],
      ['Rio Ferdinand', 'CB', 84],
      ['Chris Smalling', 'CB', 79],
      ['Jonny Evans', 'CB', 78],
      ['Patrice Evra', 'FB', 84],
      ['Antonio Valencia', 'FB', 81],
      ['Rafael', 'FB', 77],
      ['Michael Carrick', 'DM', 84],
      ['Paul Scholes', 'CM', 83],
      ['Paul Pogba', 'CM', 85],
      ['Ander Herrera', 'CM', 79],
      ['Ryan Giggs', 'WM', 80],
      ['Nani', 'WM', 80],
      ['Ashley Young', 'WM', 78],
      ['Anthony Martial', 'W', 80],
      ['Wayne Rooney', 'ST', 88],
      ['Javier Hernández', 'ST', 80],
      ['Zlatan Ibrahimović', 'ST', 85],
    ],
  },
  {
    club: 'Manchester United',
    shortName: 'MUN',
    decade: '2020s',
    kit: RED,
    formation: '4-3-3',
    players: [
      ['André Onana', 'GK', 80],
      ['Altay Bayındır', 'GK', 72],
      ['Raphaël Varane', 'CB', 84],
      ['Lisandro Martínez', 'CB', 83],
      ['Harry Maguire', 'CB', 79],
      ['Victor Lindelöf', 'CB', 78],
      ['Luke Shaw', 'FB', 82],
      ['Diogo Dalot', 'FB', 80],
      ['Aaron Wan-Bissaka', 'FB', 79],
      ['Casemiro', 'DM', 85],
      ['Scott McTominay', 'CM', 78],
      ['Bruno Fernandes', 'CM', 87],
      ['Kobbie Mainoo', 'CM', 77],
      ['Marcus Rashford', 'W', 84],
      ['Jadon Sancho', 'W', 80],
      ['Alejandro Garnacho', 'W', 80],
      ['Amad Diallo', 'W', 79],
      ['Cristiano Ronaldo', 'ST', 85],
      ['Edinson Cavani', 'ST', 82],
      ['Rasmus Højlund', 'ST', 77],
    ],
  },
  {
    club: 'Tottenham Hotspur',
    shortName: 'TOT',
    decade: '2010s',
    kit: WHITE,
    formation: '4-3-3',
    players: [
      ['Hugo Lloris', 'GK', 86],
      ['Brad Friedel', 'GK', 76],
      ['Jan Vertonghen', 'CB', 85],
      ['Toby Alderweireld', 'CB', 86],
      ['Ledley King', 'CB', 80],
      ['Younès Kaboul', 'CB', 77],
      ['Danny Rose', 'FB', 80],
      ['Ben Davies', 'FB', 78],
      ['Benoît Assou-Ekotto', 'FB', 77],
      ['Serge Aurier', 'FB', 76],
      ['Scott Parker', 'DM', 80],
      ['Eric Dier', 'DM', 79],
      ['Mousa Dembélé', 'CM', 85],
      ['Luka Modrić', 'CM', 86],
      ['Christian Eriksen', 'CM', 86],
      ['Dele Alli', 'CM', 84],
      ['Rafael van der Vaart', 'CM', 83],
      ['Gareth Bale', 'W', 89],
      ['Aaron Lennon', 'W', 78],
      ['Harry Kane', 'ST', 91],
      ['Emmanuel Adebayor', 'ST', 80],
    ],
  },
  {
    club: 'Tottenham Hotspur',
    shortName: 'TOT',
    decade: '2020s',
    kit: WHITE,
    formation: '4-3-3',
    players: [
      ['Guglielmo Vicario', 'GK', 81],
      ['Pierluigi Gollini', 'GK', 74],
      ['Cristian Romero', 'CB', 85],
      ['Micky van de Ven', 'CB', 82],
      ['Radu Drăgușin', 'CB', 76],
      ['Pedro Porro', 'FB', 81],
      ['Destiny Udogie', 'FB', 79],
      ['Sergio Reguilón', 'FB', 77],
      ['Pierre-Emile Højbjerg', 'DM', 81],
      ['Rodrigo Bentancur', 'DM', 80],
      ['James Maddison', 'CM', 83],
      ['Pape Matar Sarr', 'CM', 78],
      ['Dejan Kulusevski', 'W', 82],
      ['Son Heung-min', 'W', 89],
      ['Brennan Johnson', 'W', 78],
      ['Richarlison', 'ST', 79],
      ['Dominic Solanke', 'ST', 79],
    ],
  },
  {
    club: 'Everton',
    shortName: 'EVE',
    decade: '2010s',
    kit: ROYAL,
    formation: '4-3-3',
    players: [
      ['Tim Howard', 'GK', 81],
      ['Jordan Pickford', 'GK', 82],
      ['Phil Jagielka', 'CB', 81],
      ['Sylvain Distin', 'CB', 78],
      ['Michael Keane', 'CB', 78],
      ['Ashley Williams', 'CB', 76],
      ['Leighton Baines', 'FB', 84],
      ['Séamus Coleman', 'FB', 81],
      ['Tony Hibbert', 'FB', 72],
      ['Idrissa Gueye', 'DM', 81],
      ['Gareth Barry', 'DM', 79],
      ['James McCarthy', 'CM', 77],
      ['Marouane Fellaini', 'CM', 80],
      ['Ross Barkley', 'CM', 78],
      ['Gylfi Sigurðsson', 'CM', 80],
      ['Leon Osman', 'CM', 76],
      ['Steven Pienaar', 'W', 80],
      ['Kevin Mirallas', 'W', 78],
      ['Romelu Lukaku', 'ST', 85],
      ['Tim Cahill', 'ST', 79],
      ['Nikica Jelavić', 'ST', 76],
    ],
  },
  {
    club: 'Leicester City',
    shortName: 'LEI',
    decade: '2010s',
    kit: ROYAL,
    formation: '4-4-2',
    players: [
      ['Kasper Schmeichel', 'GK', 83],
      ['Ben Hamer', 'GK', 68],
      ['Wes Morgan', 'CB', 78],
      ['Robert Huth', 'CB', 79],
      ['Çağlar Söyüncü', 'CB', 79],
      ['Danny Simpson', 'FB', 75],
      ['Christian Fuchs', 'FB', 77],
      ['Ricardo Pereira', 'FB', 81],
      ['Wilfred Ndidi', 'DM', 82],
      ['Danny Drinkwater', 'CM', 79],
      ['Youri Tielemans', 'CM', 81],
      ['Andy King', 'CM', 74],
      ['Riyad Mahrez', 'WM', 86],
      ['Marc Albrighton', 'WM', 77],
      ['Demarai Gray', 'WM', 75],
      ['Harvey Barnes', 'W', 78],
      ['Jamie Vardy', 'ST', 85],
      ['Shinji Okazaki', 'ST', 77],
      ['Kelechi Iheanacho', 'ST', 75],
      ['Leonardo Ulloa', 'ST', 72],
    ],
  },
  {
    club: 'Southampton',
    shortName: 'SOU',
    decade: '2010s',
    kit: RED,
    formation: '4-4-2',
    players: [
      ['Fraser Forster', 'GK', 79],
      ['Artur Boruc', 'GK', 74],
      ['José Fonte', 'CB', 79],
      ['Maya Yoshida', 'CB', 76],
      ['Jan Bednarek', 'CB', 76],
      ['Nathaniel Clyne', 'FB', 80],
      ['Ryan Bertrand', 'FB', 80],
      ['Cédric Soares', 'FB', 77],
      ['Morgan Schneiderlin', 'DM', 82],
      ['Victor Wanyama', 'DM', 80],
      ['Oriol Romeu', 'DM', 77],
      ['Adam Lallana', 'CM', 82],
      ['James Ward-Prowse', 'CM', 81],
      ['Steven Davis', 'CM', 77],
      ['Dušan Tadić', 'WM', 82],
      ['Nathan Redmond', 'WM', 76],
      ['Jay Rodriguez', 'ST', 78],
      ['Rickie Lambert', 'ST', 79],
      ['Graziano Pellè', 'ST', 79],
      ['Danny Ings', 'ST', 79],
      ['Shane Long', 'ST', 75],
    ],
  },
  {
    club: 'Newcastle United',
    shortName: 'NEW',
    decade: '2020s',
    kit: BLACK,
    formation: '4-3-3',
    players: [
      ['Nick Pope', 'GK', 82],
      ['Martin Dúbravka', 'GK', 76],
      ['Sven Botman', 'CB', 82],
      ['Fabian Schär', 'CB', 81],
      ['Dan Burn', 'CB', 78],
      ['Jamaal Lascelles', 'CB', 75],
      ['Kieran Trippier', 'FB', 83],
      ['Tino Livramento', 'FB', 78],
      ['Lewis Hall', 'FB', 77],
      ['Bruno Guimarães', 'DM', 86],
      ['Sandro Tonali', 'CM', 82],
      ['Joelinton', 'CM', 80],
      ['Sean Longstaff', 'CM', 76],
      ['Anthony Gordon', 'W', 82],
      ['Allan Saint-Maximin', 'W', 79],
      ['Miguel Almirón', 'W', 78],
      ['Jacob Murphy', 'W', 76],
      ['Alexander Isak', 'ST', 86],
      ['Callum Wilson', 'ST', 79],
    ],
  },
  {
    club: 'Aston Villa',
    shortName: 'AVL',
    decade: '2020s',
    kit: CLARET,
    formation: '4-3-3',
    players: [
      ['Emiliano Martínez', 'GK', 86],
      ['Robin Olsen', 'GK', 72],
      ['Ezri Konsa', 'CB', 80],
      ['Pau Torres', 'CB', 81],
      ['Tyrone Mings', 'CB', 78],
      ['Diego Carlos', 'CB', 77],
      ['Matty Cash', 'FB', 79],
      ['Lucas Digne', 'FB', 79],
      ['Boubacar Kamara', 'DM', 81],
      ['Amadou Onana', 'DM', 80],
      ['Douglas Luiz', 'CM', 81],
      ['John McGinn', 'CM', 81],
      ['Jacob Ramsey', 'CM', 77],
      ['Morgan Rogers', 'W', 80],
      ['Leon Bailey', 'W', 80],
      ['Moussa Diaby', 'W', 80],
      ['Emiliano Buendía', 'W', 78],
      ['Ollie Watkins', 'ST', 84],
      ['Jhon Durán', 'ST', 76],
    ],
  },
  {
    club: 'West Ham United',
    shortName: 'WHU',
    decade: '2020s',
    kit: CLARET,
    formation: '4-3-3',
    players: [
      ['Łukasz Fabiański', 'GK', 79],
      ['Alphonse Areola', 'GK', 78],
      ['Kurt Zouma', 'CB', 80],
      ['Angelo Ogbonna', 'CB', 78],
      ['Nayef Aguerd', 'CB', 78],
      ['Craig Dawson', 'CB', 76],
      ['Vladimír Coufal', 'FB', 78],
      ['Aaron Cresswell', 'FB', 78],
      ['Emerson Palmieri', 'FB', 76],
      ['Tomáš Souček', 'DM', 80],
      ['Edson Álvarez', 'DM', 79],
      ['Lucas Paquetá', 'CM', 84],
      ['Pablo Fornals', 'CM', 77],
      ['Jarrod Bowen', 'W', 83],
      ['Mohammed Kudus', 'W', 82],
      ['Saïd Benrahma', 'W', 77],
      ['Michail Antonio', 'ST', 78],
      ['Niclas Füllkrug', 'ST', 78],
    ],
  },
  {
    club: 'Brighton & Hove Albion',
    shortName: 'BHA',
    decade: '2020s',
    kit: kit('#2a5fb0', '#ffffff', 'blue'),
    formation: '4-3-3',
    players: [
      ['Bart Verbruggen', 'GK', 78],
      ['Robert Sánchez', 'GK', 78],
      ['Lewis Dunk', 'CB', 81],
      ['Jan Paul van Hecke', 'CB', 79],
      ['Adam Webster', 'CB', 78],
      ['Pervis Estupiñán', 'FB', 80],
      ['Joël Veltman', 'FB', 77],
      ['Tariq Lamptey', 'FB', 76],
      ['Yves Bissouma', 'DM', 81],
      ['Carlos Baleba', 'DM', 79],
      ['Pascal Groß', 'CM', 81],
      ['Billy Gilmour', 'CM', 77],
      ['Kaoru Mitoma', 'W', 82],
      ['Solly March', 'W', 79],
      ['Simon Adingra', 'W', 76],
      ['João Pedro', 'ST', 81],
      ['Danny Welbeck', 'ST', 77],
      ['Evan Ferguson', 'ST', 77],
    ],
  },
  {
    club: 'Crystal Palace',
    shortName: 'CRY',
    decade: '2020s',
    kit: kit('#1b458f', '#f0c330', 'blue'),
    formation: '4-3-3',
    players: [
      ['Dean Henderson', 'GK', 80],
      ['Vicente Guaita', 'GK', 76],
      ['Marc Guéhi', 'CB', 83],
      ['Joachim Andersen', 'CB', 81],
      ['Maxence Lacroix', 'CB', 79],
      ['Chris Richards', 'CB', 76],
      ['Daniel Muñoz', 'FB', 80],
      ['Tyrick Mitchell', 'FB', 78],
      ['Joel Ward', 'FB', 75],
      ['Adam Wharton', 'DM', 80],
      ['Cheick Doucouré', 'DM', 79],
      ['Jefferson Lerma', 'CM', 78],
      ['Eberechi Eze', 'CM', 84],
      ['Luka Milivojević', 'CM', 78],
      ['Michael Olise', 'W', 83],
      ['Wilfried Zaha', 'W', 83],
      ['Ismaïla Sarr', 'W', 78],
      ['Jean-Philippe Mateta', 'ST', 80],
      ['Odsonne Édouard', 'ST', 76],
    ],
  },
]
